### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by dward2** [dward2/BME547#567]
- [ ] Create GET route for adding patient
- [ ] Write validation function
- [ ] Add to database
